server:
  port: 2022
spring:
  servlet:
    multipart:
      enabled: true #默认支持文件上传
      max-file-size: 5MB # 最大支持文件大小
      max-request-size: 5MB # 最大支持请求大小，不可省略
  application:
    name: inis_blog_syatem
  datasource:
    url: jdbc:mysql://localhost:3306/inis_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 192.168.134.20
    password: 123456
inis.blog.image.save-path: D:\IDEA\workspace\images
# 2MB
inis.blog.image.max-size: 2097152
